###
GET http://localhost:5000/match

###
POST http://localhost:5000/match/filterUsers
Content-Type: application/json

{
    "userId" : "1",
    "sexdata" : "man",
    "orientdata" : "gay",
    "fromdata" : "20",
    "toAge" : "23",
    "distancedata" : "100"
}



### below are test, not established route
POST http://localhost:5000/users
Content-Type: application/json

{
    "userId": "116551321"
}

### 
POST http://localhost:5000/users
Content-Type: application/json

{
    "username" : "linfan",
    "password" : "123456"
}

###
POST http://localhost:5000/match
Content-Type: application/json

{
    "userId" : "0"
}

###
GET https://opendata.paris.fr/explore/dataset/arrondissements


